imagePullSecrets: {}

installation:
  controlPlaneTolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/etcd"
    operator: "Exists"
    effect: "NoExecute"
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    bgp: Disabled
  imagePath: "rancher"
  imagePrefix: "mirrored-calico-"
  flexVolumePath: "/var/lib/kubelet/volumeplugins/"

apiServer:
  enabled: false

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

resources: {}

# Configuration for the tigera operator
tigeraOperator:
  image: rancher/mirrored-calico-operator
  version: v1.27.12
  registry: docker.io
calicoctl:
  image: rancher/mirrored-calico-ctl
  tag: v3.23.3

global:
  systemDefaultRegistry: ""
  clusterCIDRv4: ""
  clusterCIDRv6: ""

# Config required by Windows nodes
ipamConfig:
  strictAffinity: true
  autoAllocateBlocks: true

felixConfiguration:
  wireguardEnabled: false
  # Config required to fix RKE2 issue #1541
  featureDetectOverride: "ChecksumOffloadBroken=true"
  healthPort: 9099
